// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.1.4")]
[assembly: AssemblyFileVersionAttribute("1.1.4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.4";
    }
}
