// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.1.5")]
[assembly: AssemblyFileVersionAttribute("1.1.5")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.5";
    }
}
